### PR TITLE
CreateNewChannel

### PR DESCRIPTION
**Pull request by numuminov**
Nurulla`s new pull request

### CODE REVIEW

**Comment by numuminov** [comment]
..

**Review by adamrochwick — CHANGES_REQUESTED** [review]
For your web elements, encapsulate them first, then use public methods to get access to them for implementation.

**Review by adamrochwick — COMMENTED** [review]
Looking good now!

**Review by adamrochwick — APPROVED** [review]

**Review by adamrochwick — APPROVED** [review]

**Comment by numuminov** [comment]
..

**Review by seck1n-cyber — APPROVED** [review]

**Pull request merged**
